// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxPFW0vqqayZaZjV31R2noyKQ54LLGlA',
    appId: '1:425544577026:android:2ccf04b65b4e01159ff71b',
    messagingSenderId: '425544577026',
    projectId: 'aladdin-orders',
    databaseURL: 'https://aladdin-orders-default-rtdb.firebaseio.com',
    storageBucket: 'aladdin-orders.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1ZEhYl0O_kwTYN2min2LPky-NRFbjEc',
    appId: '1:425544577026:web:7dc603b4a020c82c9ff71b',
    messagingSenderId: '425544577026',
    projectId: 'aladdin-orders',
    authDomain: 'aladdin-orders.firebaseapp.com',
    databaseURL: 'https://aladdin-orders-default-rtdb.firebaseio.com',
    storageBucket: 'aladdin-orders.appspot.com',
    measurementId: 'G-Z1W7D40NNL',
  );

}